version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1udv7p3tlylyd"
s3_prefix = "sam-app-1"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
